workflows:
  version: 2
  nodegatsby:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - CI

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *get-cache
      - run: yarn install
      - <<: *save-cache
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn deploy:surge

  deploy:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo
    steps:
      - run: yarn deploy
      
get-cache: &get-cache
  restore_cache:
    key: dependencies-{{ checksum "package.json" }}
save-cache: &save-cache
  save_cache:
    paths:
      - node_modules
    key: dependencies-{{ checksum "package.json" }}
