version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *get-cache
      - run: yarn install
      - <<: *save-cache
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run:
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; 
            then 
              yarn deploy;
            elif
              yarn deploy:surge
            fi

get-cache: &get-cache
  restore_cache:
    key: dependencies-{{ checksum "package.json" }}
save-cache: &save-cache
  save_cache:
    paths:
      - node_modules
    key: dependencies-{{ checksum "package.json" }}
